{% set name = "torchio" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bb56bf5cb3476846565e24cc740a69de4cd6f6bb65165b9182d4ab46cd1b5d0c

build:
  number: 0
  noarch: python
  entry_points:
    - torchio-transform=torchio.cli.apply_transform:main
    - tiohd=torchio.cli.print_info:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python >=3.8, <3.13
  run:
    - python >=3.8, <3.13
    - deprecated >=1.2.5
    - humanize
    - nibabel
    - numpy >=1.15
    - python >=3.6, <3.13
    - scipy
    - simpleitk !=2.0.*,!=2.1.1.1
    - pytorch >=1.7
    - tqdm
    - typer

test:
  imports:
    - torchio
  commands:
    - pip check
    # - torchio-transform --help  ## broken
    # - tiohd --help  ## broken
  requires:
    - pip

about:
  home: https://github.com/fepegar/torchio
  summary: Tools for loading, augmenting and writing 3D medical images on PyTorch.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://torchio.readthedocs.io/index.html

extra:
  recipe-maintainers:
    - sarthakpati # https://github.com/fepegar/torchio/discussions/480#discussioncomment-455823
    - anjos
