{% set name = "torchio" %}
{% set version = "0.20.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8dacd98600cbc497a60a4a58ddd0068d7be59ada13e4c36507be349257e8603

build:
  number: 0
  noarch: python
  entry_points:
    - torchio-transform=torchio.cli.apply_transform:main
    - tiohd=torchio.cli.print_info:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.13
    - deprecated >=1.2.5
    - hatchling
    - humanize
    - nibabel
    - numpy >=1.15
    - python >={{ python_min }},<3.13
    - scipy
    - simpleitk !=2.0.*,!=2.1.1.1
    - pytorch >=1.7
    - tqdm
    - typer

test:
  imports:
    - torchio
  commands:
    - pip check
    # - torchio-transform --help  ## broken
    # - tiohd --help  ## broken
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fepegar/torchio
  summary: Tools for loading, augmenting and writing 3D medical images on PyTorch.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://torchio.readthedocs.io/index.html

extra:
  recipe-maintainers:
    - sarthakpati # https://github.com/fepegar/torchio/discussions/480#discussioncomment-455823
    - anjos
