{% set name = "torchio" %}
{% set version = "0.20.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 559a87a56753ed08ac19546ded31a75a59f7af58689672592c13878ddef37d40

build:
  number: 0
  noarch: python
  entry_points:
    - torchio-transform=torchio.cli.apply_transform:main
    - tiohd=torchio.cli.print_info:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - deprecated >=1.2
    - einops >=0.3
    - hatchling
    - humanize >=0.1
    - nibabel >=3
    - numpy >=1.20
    - packaging >=20
    - python >={{ python_min }}
    - pytorch >=1.9
    - rich >=10
    - scipy >=1.7
    - simpleitk >=1.3,!=2.0.*,!=2.1.1.1
    - tqdm >=4.40
    - typer >=0.1

test:
  imports:
    - torchio
  commands:
    - pip check
    # - torchio-transform --help  ## broken
    # - tiohd --help  ## broken
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fepegar/torchio
  summary: Tools for loading, augmenting and writing 3D medical images on PyTorch.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://torchio.readthedocs.io/index.html

extra:
  recipe-maintainers:
    - sarthakpati # https://github.com/fepegar/torchio/discussions/480#discussioncomment-455823
    - anjos
