# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: torchio
  version: "0.21.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 5769b5a447ad693c33a7249a7616be1f34ea13c247fb1668860ac42d59c9a58d

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv
  python:
    entry_points:
      - tiohd = torchio.cli.print_info:app
      - tiotr = torchio.cli.apply_transform:app
      - torchio-transform = torchio.cli.apply_transform:app

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - uv-build
  run:
    - deprecated >=1.2
    - einops >=0.3
    - humanize >=0.1
    - nibabel >=3
    - numpy >=1.20
    - packaging >=20
    - python >=${{ python_min }}
    - pytorch >=1.9
    - rich >=10
    - scipy >=1.7
    - simpleitk >=1.3,!=2.0.*,!=2.1.1.1
    - tqdm >=4.40
    - typer >=0.1

tests:
  - python:
      imports:
        - torchio
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - tiohd --help
      - tiotr --help
      - torchio-transform --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  summary: Tools for medical image processing with PyTorch
  description: |
    TorchIO is a Python package containing a set of tools to efficiently read,
    preprocess, sample, augment, and write 3D medical images in deep learning
    applications written in PyTorch, including intensity and spatial transforms
    for data augmentation and preprocessing. Transforms include typical computer
    vision operations such as random affine transformations and also
    domain-specific ones such as simulation of intensity artifacts due to MRI
    magnetic field inhomogeneity or k-space motion artifacts.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://torchio.readthedocs.io/
  repository: https://github.com/TorchIO-project/torchio
  documentation: https://torchio.readthedocs.io/

extra:
  recipe-maintainers:
    - sarthakpati # https://github.com/TorchIO-project/torchio/discussions/480#discussioncomment-455823
    - anjos
    - aywi
